<div class="space-y-4">
    <div class="grid gap-4 lg:grid-cols-3">
        <x-card><p class="text-sm text-slate-500">Patient</p><p class="font-semibold">{{ $insuranceClaim->patient?->first_name }} {{ $insuranceClaim->patient?->last_name }}</p><p class="text-sm">{{ $insuranceClaim->membership?->membership_number }}</p></x-card>
        <x-card><p class="text-sm text-slate-500">Provider</p><p class="font-semibold">{{ $insuranceClaim->provider?->name }}</p><p class="text-sm">{{ $insuranceClaim->scheme?->name }}</p></x-card>
        <x-card><p class="text-sm text-slate-500">Amounts</p><p class="font-semibold">Claimed {{ number_format($insuranceClaim->payer_claimed_amount,2) }}</p><p class="text-sm">Outstanding {{ number_format($insuranceClaim->outstanding_amount,2) }}</p></x-card>
    </div>
    <x-card><h3 class="font-semibold">Claim Items</h3><div class="mt-3 overflow-x-auto"><table class="min-w-full text-sm"><thead class="text-left text-xs uppercase text-slate-500"><tr><th class="px-3 py-2">Description</th><th class="px-3 py-2">Qty</th><th class="px-3 py-2">Gross</th><th class="px-3 py-2">Patient</th><th class="px-3 py-2">Claimed</th><th class="px-3 py-2">Status</th></tr></thead><tbody>@foreach($insuranceClaim->items as $item)<tr class="border-t border-slate-100 dark:border-slate-800"><td class="px-3 py-2">{{ $item->description_snapshot }}</td><td class="px-3 py-2">{{ $item->quantity }}</td><td class="px-3 py-2">{{ number_format($item->gross_amount,2) }}</td><td class="px-3 py-2">{{ number_format($item->patient_amount,2) }}</td><td class="px-3 py-2">{{ number_format($item->claimed_amount,2) }}</td><td class="px-3 py-2">{{ $item->status }}</td></tr>@endforeach</tbody></table></div></x-card>
    <x-card><h3 class="font-semibold">Foundation Notice</h3><p class="mt-2 text-sm text-slate-500">This report is a facility claim management record. It is not labelled as an official electronic NHIF submission format unless a verified template is configured.</p></x-card>
</div>
