<?php

namespace App\Services;

use App\Enums\ObservationAdmissionStatus;
use App\Enums\PatientStatus;
use App\Enums\VisitStatus;
use App\Models\ActivityLog;
use App\Models\ObservationAbscondedRecord;
use App\Models\ObservationAdmission;
use App\Models\ObservationDeathRecord;
use App\Models\ObservationDischarge;
use App\Models\ObservationLamaRecord;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class ObservationDischargeService
{
    public function __construct(private readonly BedManagementService $beds, private readonly ObservationBillingService $billing) {}
    public function validateDischargeReadiness(ObservationAdmission $a): void { if (! $a->isActive()) throw ValidationException::withMessages(['admission'=>'Admission si active.']); }
    public function finalizeCharges(ObservationAdmission $a, $actor): void { $this->billing->finalizeDischargeCharges($a, $actor); }
    public function completePendingOrders(ObservationAdmission $a, $actor): void { $a->orders()->whereIn('status',['pending','acknowledged','in_progress'])->update(['status'=>'completed','completed_at'=>now(),'completed_by'=>$actor->id]); }
    public function createFollowUp(ObservationDischarge $d): void {}
    public function releaseBed(ObservationAdmission $a, $actor): void { $this->beds->releaseBed($a, $actor); }
    public function completeVisit(ObservationAdmission $a, string $status = 'discharged'): void { $a->visit->update(['visit_status'=>$status === 'referred' ? VisitStatus::Referred : VisitStatus::Discharged, 'completed_at'=>now()]); }
    public function discharge(ObservationAdmission $a, array $data, $actor): ObservationDischarge { return DB::transaction(function () use ($a,$data,$actor): ObservationDischarge { $this->validateDischargeReadiness($a); if (($data['follow_up_required'] ?? false) && empty($data['follow_up_date'])) throw ValidationException::withMessages(['follow_up_date'=>'Follow-up date inahitajika.']); $this->completePendingOrders($a,$actor); $this->finalizeCharges($a,$actor); $d = ObservationDischarge::query()->create(['facility_id'=>$a->facility_id,'observation_admission_id'=>$a->id,'patient_id'=>$a->patient_id,'visit_id'=>$a->visit_id,'discharge_type'=>$data['discharge_type'],'discharge_condition'=>$data['discharge_condition'],'final_diagnosis'=>$data['final_diagnosis'] ?? $a->final_diagnosis,'treatment_summary'=>$data['treatment_summary'] ?? null,'procedures_summary'=>$data['procedures_summary'] ?? null,'medications_on_discharge'=>$data['medications_on_discharge'] ?? null,'follow_up_required'=>(bool)($data['follow_up_required'] ?? false),'follow_up_date'=>$data['follow_up_date'] ?? null,'follow_up_department_id'=>$data['follow_up_department_id'] ?? null,'discharge_instructions'=>$data['discharge_instructions'] ?? null,'warning_signs'=>$data['warning_signs'] ?? null,'discharged_by'=>$actor->id,'authorized_by'=>$data['authorized_by'] ?? null,'discharged_at'=>$data['discharged_at'] ?? now(),'billing_status'=>$data['billing_status'] ?? null,'notes'=>$data['notes'] ?? null,'created_by'=>$actor->id]); $a->update(['status'=>ObservationAdmissionStatus::Discharged,'actual_discharge_at'=>$d->discharged_at,'final_diagnosis'=>$d->final_diagnosis,'updated_by'=>$actor->id]); $this->releaseBed($a,$actor); $this->completeVisit($a); ActivityLog::query()->create(['user_id'=>$actor->id,'event'=>'observation_discharged','subject_type'=>$d::class,'subject_id'=>$d->id]); return $d; }); }
    public function recordLama(ObservationAdmission $a, array $data, $actor): ObservationLamaRecord { return DB::transaction(function () use ($a,$data,$actor) { if (blank($data['lama_reason'] ?? null) || blank($data['counselling_notes'] ?? null)) throw ValidationException::withMessages(['lama_reason'=>'Sababu na counselling zinahitajika.']); $r=ObservationLamaRecord::query()->create(['facility_id'=>$a->facility_id,'observation_admission_id'=>$a->id,'patient_id'=>$a->patient_id,'lama_reason'=>$data['lama_reason'],'counselling_notes'=>$data['counselling_notes'],'risks_explained'=>$data['risks_explained'] ?? null,'patient_or_guardian_name'=>$data['patient_or_guardian_name'],'witness_user_id'=>$data['witness_user_id'] ?? null,'acknowledged_at'=>$data['acknowledged_at'] ?? now(),'recorded_by'=>$actor->id]); $a->update(['status'=>ObservationAdmissionStatus::LeftAgainstMedicalAdvice,'actual_discharge_at'=>now()]); $this->releaseBed($a,$actor); ActivityLog::query()->create(['user_id'=>$actor->id,'event'=>'observation_lama_recorded','subject_type'=>$r::class,'subject_id'=>$r->id]); return $r; }); }
    public function recordAbsconded(ObservationAdmission $a, array $data, $actor): ObservationAbscondedRecord { $r=ObservationAbscondedRecord::query()->create(['facility_id'=>$a->facility_id,'observation_admission_id'=>$a->id,'patient_id'=>$a->patient_id,'last_seen_at'=>$data['last_seen_at'],'last_known_condition'=>$data['last_known_condition'] ?? null,'discovered_by'=>$actor->id,'actions_taken'=>$data['actions_taken'] ?? null,'guardian_contacted'=>(bool)($data['guardian_contacted'] ?? false),'management_notified'=>(bool)($data['management_notified'] ?? false),'notes'=>$data['notes'] ?? null]); $a->update(['status'=>ObservationAdmissionStatus::Absconded]); ActivityLog::query()->create(['user_id'=>$actor->id,'event'=>'observation_absconded','subject_type'=>$r::class,'subject_id'=>$r->id]); return $r; }
    public function recordDeath(ObservationAdmission $a, array $data, $actor): ObservationDeathRecord { return DB::transaction(function () use ($a,$data,$actor) { $r=ObservationDeathRecord::query()->create(['facility_id'=>$a->facility_id,'observation_admission_id'=>$a->id,'patient_id'=>$a->patient_id,'visit_id'=>$a->visit_id,'declared_by'=>$actor->id,'declared_at'=>$data['declared_at'] ?? now(),'suspected_cause'=>$data['suspected_cause'] ?? null,'circumstances'=>$data['circumstances'] ?? null,'resuscitation_attempted'=>(bool)($data['resuscitation_attempted'] ?? false),'resuscitation_notes'=>$data['resuscitation_notes'] ?? null,'next_of_kin_notified'=>(bool)($data['next_of_kin_notified'] ?? false),'notified_by'=>$data['notified_by'] ?? null,'notified_at'=>$data['notified_at'] ?? null,'body_released_to'=>$data['body_released_to'] ?? null,'notes'=>$data['notes'] ?? null]); $a->update(['status'=>ObservationAdmissionStatus::Deceased,'actual_discharge_at'=>now()]); $a->patient->update(['patient_status'=>PatientStatus::Deceased]); $this->releaseBed($a,$actor); ActivityLog::query()->create(['user_id'=>$actor->id,'event'=>'observation_death_recorded','subject_type'=>$r::class,'subject_id'=>$r->id]); return $r; }); }
}
