<div class="space-y-5">
    <x-card><div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 class="text-lg font-semibold">{{ $visit->patient->fullName() }}</h2><p class="text-sm text-slate-500">{{ $visit->patient->patient_number }} · {{ $visit->patient->ageLabel() }} · {{ $visit->patient->gender->label() }} · {{ $visit->payer_type?->label() }}</p><p class="text-xs text-red-600">Allergies: {{ $visit->patient->known_allergies ?? '-' }}</p></div><div class="flex gap-2"><span class="text-sm text-slate-500">{{ $saveState }}</span><x-secondary-button wire:click="autosave"><x-lucide-save class="h-4 w-4" /> Draft</x-secondary-button><x-primary-button wire:click="complete">Complete</x-primary-button></div></div></x-card>
    <div class="flex flex-wrap gap-2">@foreach(['summary'=>'Summary','history'=>'History','exam'=>'Examination','odontogram'=>'Odontogram','periodontal'=>'Periodontal','diagnoses'=>'Diagnoses','plans'=>'Treatment Plan','procedures'=>'Procedures','attachments'=>'Imaging','timeline'=>'Timeline'] as $key=>$label)<button type="button" wire:click="$set('activeTab','{{ $key }}')" class="rounded-md px-3 py-2 text-sm font-semibold {{ $activeTab===$key?'bg-primary text-white':'bg-slate-100 dark:bg-slate-800' }}">{{ $label }}</button>@endforeach</div>
    @if($activeTab==='summary' || $activeTab==='history' || $activeTab==='exam')<x-card><div class="grid gap-4 md:grid-cols-2"><div><x-input-label value="Complaint" /><x-textarea wire:model.live.debounce.800ms="form.complaint" rows="3" /></div><div><x-input-label value="Dental History" /><x-textarea wire:model.live.debounce.800ms="form.dental_history" rows="3" /></div><div><x-input-label value="Extraoral Examination" /><x-textarea wire:model.live.debounce.800ms="form.extraoral_examination" rows="3" /></div><div><x-input-label value="Intraoral Examination" /><x-textarea wire:model.live.debounce.800ms="form.intraoral_examination" rows="3" /></div><div><x-input-label value="Clinical Summary" /><x-textarea wire:model.live.debounce.800ms="form.clinical_summary" rows="3" /></div><div><x-input-label value="Treatment Plan Summary" /><x-textarea wire:model.live.debounce.800ms="form.treatment_plan_summary" rows="3" /></div></div></x-card>@endif
    @if($activeTab==='odontogram')<x-card><livewire:dental.odontogram :encounter="$dentalEncounter" :key="'odontogram-'.$dentalEncounter->id" /></x-card>@endif
    @if($activeTab==='diagnoses')<x-card><div class="flex justify-between"><h3 class="font-semibold">Diagnoses</h3><x-primary-button wire:click="$set('showDiagnosisModal', true)">Ongeza</x-primary-button></div><div class="mt-3 space-y-2">@foreach($dentalEncounter->diagnoses as $d)<div class="rounded-md border border-slate-200 p-3 dark:border-slate-700">{{ $d->diagnosis_name }} @if($d->tooth_number)<span class="text-xs text-slate-500">Tooth {{ $d->tooth_number }}</span>@endif</div>@endforeach</div></x-card>@endif
    @if($activeTab==='plans')<x-card><div class="flex justify-between"><h3 class="font-semibold">Treatment Plans</h3><x-primary-button wire:click="$set('showPlanModal', true)">Mpango Mpya</x-primary-button></div><div class="mt-3 grid gap-3 md:grid-cols-2">@foreach($dentalEncounter->treatmentPlans as $plan)<div class="rounded-md border border-slate-200 p-3 dark:border-slate-700"><p class="font-semibold">{{ $plan->title }}</p><p class="text-sm">TSh {{ number_format((float)$plan->estimated_total,2) }} · {{ $plan->status?->value ?? $plan->status }}</p><a class="text-primary text-sm" href="{{ route('dental.treatment-plans.print',$plan) }}" target="_blank">Print</a></div>@endforeach</div></x-card>@endif
    @if($activeTab==='procedures')<x-card><div class="flex justify-between"><h3 class="font-semibold">Procedures</h3><x-primary-button wire:click="$set('showProcedureModal', true)">Record Procedure</x-primary-button></div><div class="mt-3 space-y-2">@foreach($dentalEncounter->procedures as $p)<div class="rounded-md border border-slate-200 p-3 dark:border-slate-700"><p class="font-semibold">{{ $p->procedure_name_snapshot }}</p><p class="text-sm">Tooth {{ $p->tooth_number ?? '-' }} · {{ $p->status?->value ?? $p->status }}</p><a class="text-primary text-sm" href="{{ route('dental.procedures.print',$p) }}" target="_blank">Report</a></div>@endforeach</div></x-card>@endif
    <x-modal :show="$showDiagnosisModal" title="Dental Diagnosis" close="$set('showDiagnosisModal', false)" maxWidth="2xl"><form wire:submit="addDiagnosis" class="space-y-4"><x-text-input wire:model="diagnosisForm.diagnosis_name" placeholder="Diagnosis" /><x-text-input wire:model="diagnosisForm.tooth_number" placeholder="Tooth number" /><x-textarea wire:model="diagnosisForm.notes" rows="3" placeholder="Notes" /><x-primary-button>Hifadhi</x-primary-button></form></x-modal>
    <x-modal :show="$showPlanModal" title="Treatment Plan" close="$set('showPlanModal', false)" maxWidth="2xl"><form wire:submit="createPlan" class="space-y-4"><x-text-input wire:model="planForm.title" placeholder="Title" /><x-textarea wire:model="planForm.description" rows="4" placeholder="Description" /><label class="flex gap-2 text-sm"><x-checkbox wire:model="planForm.consent_required" /> Consent required</label><x-primary-button>Hifadhi</x-primary-button></form></x-modal>
    <x-modal :show="$showProcedureModal" title="Dental Procedure" close="$set('showProcedureModal', false)" maxWidth="2xl"><form wire:submit="createProcedure" class="space-y-4"><x-select-input wire:model="procedureForm.service_id"><option value="">Service</option>@foreach($dentalServices as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</x-select-input><x-select-input wire:model="procedureForm.procedure_type"><option value="preventive">Preventive</option><option value="restorative">Restorative</option><option value="orthodontic">Orthodontic</option><option value="oral_surgery">Oral surgery</option><option value="cosmetic">Cosmetic</option><option value="periodontal">Periodontal</option></x-select-input><x-text-input wire:model="procedureForm.tooth_number" placeholder="Tooth number" /><x-textarea wire:model="procedureForm.technique_notes" rows="3" placeholder="Notes" /><x-primary-button>Hifadhi</x-primary-button></form></x-modal>
</div>
