<?php

use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\Billing\BillingInvoicePrintController;
use App\Http\Controllers\Billing\CashierSessionPrintController;
use App\Http\Controllers\Billing\ReceiptPrintController;
use App\Http\Controllers\FacilityDocumentController;
use App\Http\Controllers\Clinical\ClinicalEncounterPrintController;
use App\Http\Controllers\Clinical\ReferralPrintController;
use App\Http\Controllers\Dental\DentalAttachmentController;
use App\Http\Controllers\Dental\DentalChartPrintController;
use App\Http\Controllers\Dental\DentalProcedurePrintController;
use App\Http\Controllers\Dental\DentalTreatmentPlanPrintController;
use App\Http\Controllers\Laboratory\LaboratoryOrderReportController;
use App\Http\Controllers\Laboratory\LaboratoryResultPrintController;
use App\Http\Controllers\Observation\ObservationChartPrintController;
use App\Http\Controllers\Observation\ObservationDischargePrintController;
use App\Http\Controllers\Pharmacy\DispensingLabelController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\Staff\StaffDocumentController;
use App\Http\Controllers\Staff\StaffSignatureController;
use App\Http\Controllers\Staff\StaffReportExportController;
use App\Http\Controllers\Patients\PatientDocumentController;
use App\Http\Controllers\Patients\PatientCardController;
use App\Http\Controllers\Reports\PatientReportExportController;
use App\Http\Controllers\Reports\ReceptionReportExportController;
use App\Http\Controllers\Reports\TriageReportExportController;
use App\Http\Controllers\Reports\OpdReportExportController;
use App\Http\Controllers\Reports\ObservationReportExportController;
use App\Http\Controllers\Reports\DiagnosisReportExportController;
use App\Http\Controllers\Reports\LaboratoryReportExportController;
use App\Http\Controllers\Reports\PharmacyReportExportController;
use App\Http\Controllers\Reports\ReferralReportExportController;
use App\Http\Controllers\Reports\DentalReportExportController;
use App\Http\Controllers\Reports\WorkflowReportExportController;
use App\Http\Controllers\Reports\InsuranceReportExportController;
use App\Http\Controllers\Reports\BillingReportExportController;
use App\Http\Controllers\Insurance\InsuranceClaimAttachmentController;
use App\Http\Controllers\Insurance\InsuranceClaimBatchPrintController;
use App\Http\Controllers\Insurance\InsuranceClaimPrintController;
use App\Http\Controllers\Insurance\InsurancePreAuthorizationPrintController;
use App\Livewire\Clinical\LaboratoryResults as ClinicalLaboratoryResults;
use App\Livewire\CorporateAccounts\Index as CorporateAccountsIndex;
use App\Livewire\Departments\Index as DepartmentsIndex;
use App\Livewire\Dashboard\Index as DashboardIndex;
use App\Livewire\Dental\Consultation as DentalConsultation;
use App\Livewire\Dental\Dashboard as DentalDashboard;
use App\Livewire\Dental\Queue as DentalQueue;
use App\Livewire\Dental\Settings\Consents as DentalSettingsConsents;
use App\Livewire\Dental\Settings\Anaesthetics as DentalSettingsAnaesthetics;
use App\Livewire\Dental\Settings\AppointmentTypes as DentalSettingsAppointmentTypes;
use App\Livewire\Dental\Settings\Chairs as DentalSettingsChairs;
use App\Livewire\Dental\Settings\Findings as DentalSettingsFindings;
use App\Livewire\Dental\Settings\Materials as DentalSettingsMaterials;
use App\Livewire\Dental\Settings\Preferences as DentalSettingsPreferences;
use App\Livewire\Dental\Settings\ProcedureTemplates as DentalSettingsProcedureTemplates;
use App\Livewire\Dental\Settings\ProcedureTypes as DentalSettingsProcedureTypes;
use App\Livewire\Dental\Settings\Rooms as DentalSettingsRooms;
use App\Livewire\Dental\Settings\Services as DentalSettingsServices;
use App\Livewire\Facility\SetupWizard;
use App\Livewire\InsuranceProviders\Index as InsuranceProvidersIndex;
use App\Livewire\Billing\Dashboard as BillingDashboard;
use App\Livewire\Billing\Queue as BillingQueue;
use App\Livewire\Billing\Cashier\Dashboard as CashierDashboard;
use App\Livewire\Billing\Cashier\SessionShow as CashierSessionShow;
use App\Livewire\Billing\Cashier\Sessions as CashierSessions;
use App\Livewire\Billing\Invoices\Index as BillingInvoicesIndex;
use App\Livewire\Billing\Invoices\Show as BillingInvoiceShow;
use App\Livewire\Billing\Reports\Index as BillingReport;
use App\Livewire\Billing\Settings\PaymentMethods as BillingPaymentMethods;
use App\Livewire\Billing\Settings\Preferences as BillingPreferences;
use App\Livewire\Insurance\Dashboard as InsuranceDashboard;
use App\Livewire\Insurance\Memberships\Index as InsuranceMembershipsIndex;
use App\Livewire\Insurance\Memberships\Show as InsuranceMembershipShow;
use App\Livewire\Insurance\PreAuthorizations\Index as InsurancePreAuthorizationsIndex;
use App\Livewire\Insurance\PreAuthorizations\Show as InsurancePreAuthorizationShow;
use App\Livewire\Insurance\Claims\Index as InsuranceClaimsIndex;
use App\Livewire\Insurance\Claims\Show as InsuranceClaimShow;
use App\Livewire\Insurance\Batches\Index as InsuranceBatchesIndex;
use App\Livewire\Insurance\Batches\Show as InsuranceBatchShow;
use App\Livewire\Insurance\Payments\Index as InsurancePaymentsIndex;
use App\Livewire\Insurance\Payments\Show as InsurancePaymentShow;
use App\Livewire\Insurance\Reconciliation\Index as InsuranceReconciliationIndex;
use App\Livewire\Insurance\Reports\NhifClaimReport;
use App\Livewire\Insurance\Settings\Providers as InsuranceSettingsProviders;
use App\Livewire\Insurance\Settings\Schemes as InsuranceSettingsSchemes;
use App\Livewire\Insurance\Settings\BenefitPackages as InsuranceSettingsBenefitPackages;
use App\Livewire\Insurance\Settings\MembershipPlans as InsuranceSettingsMembershipPlans;
use App\Livewire\Insurance\Settings\CoverageRules as InsuranceSettingsCoverageRules;
use App\Livewire\Insurance\Settings\ServiceCoverage as InsuranceSettingsServiceCoverage;
use App\Livewire\Insurance\Settings\MedicineCoverage as InsuranceSettingsMedicineCoverage;
use App\Livewire\Insurance\Settings\ContractPrices as InsuranceSettingsContractPrices;
use App\Livewire\Insurance\Settings\ServiceCodes as InsuranceSettingsServiceCodes;
use App\Livewire\Insurance\Settings\ProcedureCodes as InsuranceSettingsProcedureCodes;
use App\Livewire\Insurance\Settings\MedicineCodes as InsuranceSettingsMedicineCodes;
use App\Livewire\Insurance\Settings\ClaimRules as InsuranceSettingsClaimRules;
use App\Livewire\Insurance\Settings\RejectionReasons as InsuranceSettingsRejectionReasons;
use App\Livewire\Insurance\Settings\Preferences as InsuranceSettingsPreferences;
use App\Livewire\JobTitles\Index as JobTitlesIndex;
use App\Livewire\Laboratory\Categories\Index as LaboratoryCategoriesIndex;
use App\Livewire\Laboratory\CriticalResults as LaboratoryCriticalResults;
use App\Livewire\Laboratory\Dashboard as LaboratoryDashboard;
use App\Livewire\Laboratory\OrderShow as LaboratoryOrderShow;
use App\Livewire\Laboratory\Queue as LaboratoryQueue;
use App\Livewire\Laboratory\ResultEntry as LaboratoryResultEntry;
use App\Livewire\Laboratory\Specimens\Index as LaboratorySpecimensIndex;
use App\Livewire\Laboratory\Tests\Index as LaboratoryTestsIndex;
use App\Livewire\Laboratory\Tests\Show as LaboratoryTestShow;
use App\Livewire\Laboratory\VerifyResult as LaboratoryVerifyResult;
use App\Livewire\Permissions\Index as PermissionsIndex;
use App\Livewire\Opd\Consultation as OpdConsultation;
use App\Livewire\Opd\Dashboard as OpdDashboard;
use App\Livewire\Opd\Queue as OpdQueue;
use App\Livewire\Observation\AdmissionShow as ObservationAdmissionShow;
use App\Livewire\Observation\BedBoard as ObservationBedBoard;
use App\Livewire\Observation\Dashboard as ObservationDashboard;
use App\Livewire\Observation\Queue as ObservationQueue;
use App\Livewire\Observation\Settings\Beds as ObservationSettingsBeds;
use App\Livewire\Observation\Settings\Billing as ObservationSettingsBilling;
use App\Livewire\Observation\Settings\Rooms as ObservationSettingsRooms;
use App\Livewire\Observation\Settings\Services as ObservationSettingsServices;
use App\Livewire\Patients\Index as PatientsIndex;
use App\Livewire\Patients\Show as PatientShow;
use App\Livewire\Pharmacy\Adjustments\Index as PharmacyAdjustmentsIndex;
use App\Livewire\Pharmacy\Dashboard as PharmacyDashboard;
use App\Livewire\Pharmacy\DispensePrescription as PharmacyDispensePrescription;
use App\Livewire\Pharmacy\Medicines\Index as PharmacyMedicinesIndex;
use App\Livewire\Pharmacy\Medicines\StockCard as PharmacyMedicineStockCard;
use App\Livewire\Pharmacy\OpeningStock as PharmacyOpeningStock;
use App\Livewire\Pharmacy\PrescriptionShow as PharmacyPrescriptionShow;
use App\Livewire\Pharmacy\Purchases\Index as PharmacyPurchasesIndex;
use App\Livewire\Pharmacy\Purchases\Show as PharmacyPurchaseShow;
use App\Livewire\Pharmacy\Queue as PharmacyQueue;
use App\Livewire\Pharmacy\Receipts\Create as PharmacyReceiptCreate;
use App\Livewire\Pharmacy\Receipts\Index as PharmacyReceiptsIndex;
use App\Livewire\Pharmacy\Receipts\Show as PharmacyReceiptShow;
use App\Livewire\Pharmacy\Returns\Index as PharmacyReturnsIndex;
use App\Livewire\Pharmacy\Setup\Index as PharmacySetupIndex;
use App\Livewire\Pharmacy\StockCounts\Index as PharmacyStockCountsIndex;
use App\Livewire\Pharmacy\StockCounts\Show as PharmacyStockCountShow;
use App\Livewire\Pharmacy\Transfers\Index as PharmacyTransfersIndex;
use App\Livewire\Pharmacy\Transfers\Show as PharmacyTransferShow;
use App\Livewire\Reception\Index as ReceptionIndex;
use App\Livewire\Reception\Queue as ReceptionQueue;
use App\Livewire\Reports\Patients as PatientsReport;
use App\Livewire\Reports\Reception as ReceptionReport;
use App\Livewire\Reports\Triage as TriageReport;
use App\Livewire\Reports\Opd as OpdReport;
use App\Livewire\Reports\Observation\Index as ObservationReport;
use App\Livewire\Reports\Diagnoses as DiagnosesReport;
use App\Livewire\Reports\Dental as DentalReport;
use App\Livewire\Reports\Laboratory as LaboratoryReport;
use App\Livewire\Reports\Pharmacy as PharmacyReport;
use App\Livewire\Reports\Referrals as ReferralsReport;
use App\Livewire\Reports\Staff as StaffReport;
use App\Livewire\Reports\Workflow as WorkflowReport;
use App\Livewire\Reports\Insurance as InsuranceReport;
use App\Livewire\Roles\Index as RolesIndex;
use App\Livewire\Roles\ManagePermissions;
use App\Livewire\Services\Categories\Index as ServiceCategoriesIndex;
use App\Livewire\Services\Index as ServicesIndex;
use App\Livewire\Services\ManagePrices;
use App\Livewire\Settings\Facility\Index as FacilitySettingsIndex;
use App\Livewire\Settings\Workflow\Index as WorkflowSettingsIndex;
use App\Livewire\Staff\Index as StaffIndex;
use App\Livewire\Staff\Show as StaffShow;
use App\Livewire\Triage\Assessment as TriageAssessment;
use App\Livewire\Triage\Queue as TriageQueue;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('dashboard');
});

Route::middleware('guest')->group(function (): void {
    Route::get('login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('login', [AuthenticatedSessionController::class, 'store']);
    Route::get('forgot-password', [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('forgot-password', [PasswordResetLinkController::class, 'store'])->name('password.email');
    Route::get('reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('reset-password', [NewPasswordController::class, 'store'])->name('password.store');
});

Route::middleware(['auth', 'active.user'])->group(function (): void {
    Route::get('facility/setup', SetupWizard::class)->name('facility.setup');
    Route::get('profile', [ProfileController::class, 'show'])->name('profile.show');
    Route::get('profile/password', [ProfileController::class, 'password'])->name('profile.password');
    Route::post('logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');

    Route::middleware('facility.setup.completed')->group(function (): void {
        Route::get('dashboard', DashboardIndex::class)->name('dashboard');
        Route::view('coming-soon', 'coming-soon')->name('coming-soon');
        Route::get('settings/facility', FacilitySettingsIndex::class)->middleware('permission:facility.view')->name('settings.facility');
        Route::get('settings/workflow', WorkflowSettingsIndex::class)->middleware('permission:workflow.manage-settings')->name('settings.workflow');
        Route::get('settings/facility/documents/{document}/view', [FacilityDocumentController::class, 'view'])->name('settings.facility.documents.view');
        Route::get('settings/facility/documents/{document}/download', [FacilityDocumentController::class, 'download'])->name('settings.facility.documents.download');
        Route::get('settings/departments', DepartmentsIndex::class)->middleware('permission:departments.view')->name('settings.departments.index');
        Route::get('settings/job-titles', JobTitlesIndex::class)->middleware('permission:job-titles.view')->name('settings.job-titles.index');
        Route::get('settings/roles', RolesIndex::class)->middleware('permission:roles.view')->name('settings.roles.index');
        Route::get('settings/roles/{role}/permissions', ManagePermissions::class)->middleware('permission:roles.assign-permissions')->name('settings.roles.permissions');
        Route::get('settings/permissions', PermissionsIndex::class)->middleware('permission:permissions.view')->name('settings.permissions.index');
        Route::get('staff', StaffIndex::class)->middleware('permission:staff.view')->name('staff.index');
        Route::get('staff/{staffProfile}', StaffShow::class)->middleware('permission:staff.view')->name('staff.show');
        Route::get('staff/{staffProfile}/documents/{document}/view', [StaffDocumentController::class, 'view'])->name('staff.documents.view');
        Route::get('staff/{staffProfile}/documents/{document}/download', [StaffDocumentController::class, 'download'])->name('staff.documents.download');
        Route::get('staff/{staffProfile}/signatures/{signature}/view', [StaffSignatureController::class, 'view'])->name('staff.signatures.view');
        Route::get('reports/staff', StaffReport::class)->middleware('permission:staff.export|reports.view')->name('reports.staff');
        Route::get('reports/staff/export', StaffReportExportController::class)->middleware('permission:staff.export|reports.view')->name('reports.staff.export');
        Route::get('reports/workflow', WorkflowReport::class)->middleware('permission:workflow.reports.view')->name('reports.workflow');
        Route::get('reports/workflow/export', WorkflowReportExportController::class)->middleware('permission:workflow.reports.export')->name('reports.workflow.export');
        Route::get('settings/service-categories', ServiceCategoriesIndex::class)->middleware('permission:service-categories.view')->name('settings.service-categories.index');
        Route::get('settings/services', ServicesIndex::class)->middleware('permission:services.view')->name('settings.services.index');
        Route::get('settings/services/{service}/prices', ManagePrices::class)->middleware('permission:services.manage-prices')->name('settings.services.prices');
        Route::get('settings/insurance-providers', InsuranceProvidersIndex::class)->middleware('permission:insurance-providers.view')->name('settings.insurance-providers.index');
        Route::get('insurance/dashboard', InsuranceDashboard::class)->middleware('permission:insurance.view-dashboard')->name('insurance.dashboard');
        Route::get('insurance/memberships', InsuranceMembershipsIndex::class)->middleware('permission:insurance.view-memberships')->name('insurance.memberships.index');
        Route::get('insurance/memberships/{membership}', InsuranceMembershipShow::class)->middleware('permission:insurance.view-memberships')->name('insurance.memberships.show');
        Route::get('insurance/pre-authorizations', InsurancePreAuthorizationsIndex::class)->middleware('permission:insurance.pre-authorizations.view')->name('insurance.pre-authorizations.index');
        Route::get('insurance/pre-authorizations/{preAuthorization}', InsurancePreAuthorizationShow::class)->middleware('permission:insurance.pre-authorizations.view')->name('insurance.pre-authorizations.show');
        Route::get('insurance/pre-authorizations/{preAuthorization}/print', InsurancePreAuthorizationPrintController::class)->middleware('permission:insurance.pre-authorizations.view')->name('insurance.pre-authorizations.print');
        Route::get('insurance/claims', InsuranceClaimsIndex::class)->middleware('permission:insurance.claims.view')->name('insurance.claims.index');
        Route::get('insurance/claims/reports/nhif', NhifClaimReport::class)->middleware('permission:insurance.reports.view')->name('insurance.claims.reports.nhif');
        Route::get('insurance/claims/{insuranceClaim}', InsuranceClaimShow::class)->middleware('permission:insurance.claims.view')->name('insurance.claims.show');
        Route::get('insurance/claims/{insuranceClaim}/print', InsuranceClaimPrintController::class)->middleware('permission:insurance.claims.print')->name('insurance.claims.print');
        Route::get('insurance/claim-batches', InsuranceBatchesIndex::class)->middleware('permission:insurance.claim-batches.view')->name('insurance.claim-batches.index');
        Route::get('insurance/claim-batches/{claimBatch}', InsuranceBatchShow::class)->middleware('permission:insurance.claim-batches.view')->name('insurance.claim-batches.show');
        Route::get('insurance/claim-batches/{claimBatch}/print', InsuranceClaimBatchPrintController::class)->middleware('permission:insurance.claim-batches.view')->name('insurance.claim-batches.print');
        Route::get('insurance/payments', InsurancePaymentsIndex::class)->middleware('permission:insurance.payments.view')->name('insurance.payments.index');
        Route::get('insurance/payments/{insurancePayment}', InsurancePaymentShow::class)->middleware('permission:insurance.payments.view')->name('insurance.payments.show');
        Route::get('insurance/reconciliation', InsuranceReconciliationIndex::class)->middleware('permission:insurance.reconciliation.manage')->name('insurance.reconciliation.index');
        Route::get('insurance/claim-attachments/{claimAttachment}/view', [InsuranceClaimAttachmentController::class, 'view'])->middleware('permission:insurance.attachments.view')->name('insurance.claim-attachments.view');
        Route::get('insurance/claim-attachments/{claimAttachment}/download', [InsuranceClaimAttachmentController::class, 'download'])->middleware('permission:insurance.attachments.view')->name('insurance.claim-attachments.download');
        Route::get('settings/insurance/providers', InsuranceSettingsProviders::class)->middleware('permission:insurance.manage-providers')->name('settings.insurance.providers');
        Route::get('settings/insurance/schemes', InsuranceSettingsSchemes::class)->middleware('permission:insurance.manage-schemes')->name('settings.insurance.schemes');
        Route::get('settings/insurance/benefit-packages', InsuranceSettingsBenefitPackages::class)->middleware('permission:insurance.manage-benefit-packages')->name('settings.insurance.benefit-packages');
        Route::get('settings/insurance/membership-plans', InsuranceSettingsMembershipPlans::class)->middleware('permission:insurance.manage-membership-plans')->name('settings.insurance.membership-plans');
        Route::get('settings/insurance/coverage-rules', InsuranceSettingsCoverageRules::class)->middleware('permission:insurance.manage-coverage')->name('settings.insurance.coverage-rules');
        Route::get('settings/insurance/service-coverage', InsuranceSettingsServiceCoverage::class)->middleware('permission:insurance.manage-coverage')->name('settings.insurance.service-coverage');
        Route::get('settings/insurance/medicine-coverage', InsuranceSettingsMedicineCoverage::class)->middleware('permission:insurance.manage-coverage')->name('settings.insurance.medicine-coverage');
        Route::get('settings/insurance/diagnosis-codes', InsuranceSettingsServiceCodes::class)->middleware('permission:insurance.manage-service-codes')->name('settings.insurance.diagnosis-codes');
        Route::get('settings/insurance/procedure-codes', InsuranceSettingsProcedureCodes::class)->middleware('permission:insurance.manage-service-codes')->name('settings.insurance.procedure-codes');
        Route::get('settings/insurance/claim-rules', InsuranceSettingsClaimRules::class)->middleware('permission:insurance.manage-claim-rules')->name('settings.insurance.claim-rules');
        Route::get('settings/insurance/pre-authorization-rules', InsuranceSettingsClaimRules::class)->middleware('permission:insurance.manage-claim-rules')->name('settings.insurance.pre-authorization-rules');
        Route::get('settings/insurance/rejection-reasons', InsuranceSettingsRejectionReasons::class)->middleware('permission:insurance.manage-claim-rules')->name('settings.insurance.rejection-reasons');
        Route::get('settings/insurance/claim-statuses', InsuranceSettingsPreferences::class)->middleware('permission:insurance.manage-settings')->name('settings.insurance.claim-statuses');
        Route::get('settings/insurance/claim-attachments', InsuranceSettingsPreferences::class)->middleware('permission:insurance.manage-settings')->name('settings.insurance.claim-attachments');
        Route::get('settings/insurance/contract-prices', InsuranceSettingsContractPrices::class)->middleware('permission:insurance.manage-contract-prices')->name('settings.insurance.contract-prices');
        Route::get('settings/insurance/service-codes', InsuranceSettingsServiceCodes::class)->middleware('permission:insurance.manage-service-codes')->name('settings.insurance.service-codes');
        Route::get('settings/insurance/medicine-codes', InsuranceSettingsMedicineCodes::class)->middleware('permission:insurance.manage-medicine-codes')->name('settings.insurance.medicine-codes');
        Route::get('settings/insurance/preferences', InsuranceSettingsPreferences::class)->middleware('permission:insurance.manage-settings')->name('settings.insurance.preferences');
        Route::get('settings/insurance/report-settings', InsuranceSettingsPreferences::class)->middleware('permission:insurance.manage-settings')->name('settings.insurance.report-settings');
        Route::get('settings/corporate-accounts', CorporateAccountsIndex::class)->middleware('permission:corporate-accounts.view')->name('settings.corporate-accounts.index');
        Route::get('billing', BillingQueue::class)->middleware('permission:billing.view-queue')->name('billing.index');
        Route::get('billing/dashboard', BillingDashboard::class)->middleware('permission:billing.view-dashboard')->name('billing.dashboard');
        Route::get('billing/invoices', BillingInvoicesIndex::class)->middleware('permission:billing.view-invoice')->name('billing.invoices.index');
        Route::get('billing/invoices/{invoice}', BillingInvoiceShow::class)->middleware('permission:billing.view-invoice')->name('billing.invoices.show');
        Route::get('billing/invoices/{invoice}/print', BillingInvoicePrintController::class)->middleware('permission:billing.print-invoice')->name('billing.invoices.print');
        Route::get('billing/receipts/{receipt}/print', ReceiptPrintController::class)->middleware('permission:billing.reprint-receipt|billing.receive-payment')->name('billing.receipts.print');
        Route::get('billing/deposits', BillingReport::class)->middleware('permission:billing.deposits.view')->defaults('type', 'deposits')->name('billing.deposits.index');
        Route::get('billing/credit-patients', BillingReport::class)->middleware('permission:billing.credit-profiles.view')->defaults('type', 'credit-patients')->name('billing.credit-patients.index');
        Route::get('billing/refunds', BillingReport::class)->middleware('permission:billing.request-refund|billing.process-refund')->defaults('type', 'refunds')->name('billing.refunds.index');
        Route::get('billing/reversals', BillingReport::class)->middleware('permission:billing.request-reversal|billing.process-reversal')->defaults('type', 'reversals')->name('billing.reversals.index');
        Route::get('cashier', CashierDashboard::class)->middleware('permission:billing.access')->name('cashier.dashboard');
        Route::get('cashier/sessions', CashierSessions::class)->middleware('permission:cashier.sessions.view')->name('cashier.sessions.index');
        Route::get('cashier/sessions/{cashierSession}', CashierSessionShow::class)->middleware('permission:cashier.sessions.view')->name('cashier.sessions.show');
        Route::get('cashier/sessions/{cashierSession}/print', CashierSessionPrintController::class)->middleware('permission:cashier.sessions.view')->name('cashier.sessions.print');
        Route::get('patients', PatientsIndex::class)->middleware('permission:patients.view')->name('patients.index');
        Route::get('patients/{patient}', PatientShow::class)->middleware('permission:patients.view')->name('patients.show');
        Route::get('patients/{patient}/card', PatientCardController::class)->middleware('permission:patients.print-card')->name('patients.card');
        Route::get('patients/{patient}/documents/{document}/view', [PatientDocumentController::class, 'view'])->name('patients.documents.view');
        Route::get('patients/{patient}/documents/{document}/download', [PatientDocumentController::class, 'download'])->name('patients.documents.download');
        Route::get('reception', ReceptionIndex::class)->middleware('permission:reception.access')->name('reception.index');
        Route::get('reception/queue', ReceptionQueue::class)->middleware('permission:reception.manage-queue')->name('reception.queue');
        Route::get('triage', TriageQueue::class)->middleware('permission:triage.access')->name('triage.index');
        Route::get('triage/{visit}', TriageAssessment::class)->middleware('permission:triage.record-vitals')->name('triage.assessment');
        Route::get('opd', OpdQueue::class)->middleware('permission:opd.view-queue')->name('opd.index');
        Route::get('opd/dashboard', OpdDashboard::class)->middleware('permission:opd.access')->name('opd.dashboard');
        Route::get('opd/consultations/{visit}', OpdConsultation::class)->middleware('permission:opd.consult')->name('opd.consultation');
        Route::get('dental', DentalQueue::class)->middleware('permission:dental.view-queue')->name('dental.index');
        Route::get('dental/dashboard', DentalDashboard::class)->middleware('permission:dental.view-dashboard')->name('dental.dashboard');
        Route::get('dental/consultations/{visit}', DentalConsultation::class)->middleware('permission:dental.consult')->name('dental.consultation');
        Route::get('dental/encounters/{dentalEncounter}/chart/print', DentalChartPrintController::class)->middleware('permission:dental.print-chart')->name('dental.chart.print');
        Route::get('dental/treatment-plans/{dentalTreatmentPlan}/print', DentalTreatmentPlanPrintController::class)->middleware('permission:dental.print-treatment-plan')->name('dental.treatment-plans.print');
        Route::get('dental/procedures/{dentalProcedure}/print', DentalProcedurePrintController::class)->middleware('permission:dental.print-procedure-report')->name('dental.procedures.print');
        Route::get('dental/attachments/{dentalAttachment}/view', [DentalAttachmentController::class, 'view'])->middleware('permission:dental.manage-attachments')->name('dental.attachments.view');
        Route::get('dental/attachments/{dentalAttachment}/download', [DentalAttachmentController::class, 'download'])->middleware('permission:dental.manage-attachments')->name('dental.attachments.download');
        Route::get('observation', ObservationQueue::class)->middleware('permission:observation.access')->name('observation.index');
        Route::get('observation/dashboard', ObservationDashboard::class)->middleware('permission:observation.view-dashboard')->name('observation.dashboard');
        Route::get('observation/bed-board', ObservationBedBoard::class)->middleware('permission:observation.view-bed-board')->name('observation.bed-board');
        Route::get('observation/admissions/{observationAdmission}', ObservationAdmissionShow::class)->middleware('permission:observation.view-admission')->name('observation.admissions.show');
        Route::get('observation/admissions/{observationAdmission}/chart/print', ObservationChartPrintController::class)->middleware('permission:observation.print-chart')->name('observation.chart.print');
        Route::get('observation/discharges/{observationDischarge}/print', ObservationDischargePrintController::class)->middleware('permission:observation.print-discharge')->name('observation.discharges.print');
        Route::get('clinical-encounters/{encounter}/print', ClinicalEncounterPrintController::class)->middleware('permission:clinical-encounters.print')->name('clinical-encounters.print');
        Route::get('referrals/{referral}/print', ReferralPrintController::class)->middleware('permission:referrals.print')->name('referrals.print');
        Route::get('laboratory', LaboratoryQueue::class)->middleware('permission:laboratory.view-queue')->name('laboratory.index');
        Route::get('laboratory/dashboard', LaboratoryDashboard::class)->middleware('permission:laboratory.view-dashboard')->name('laboratory.dashboard');
        Route::get('laboratory/orders/{laboratoryOrder}', LaboratoryOrderShow::class)->middleware('permission:laboratory.view-order')->name('laboratory.orders.show');
        Route::get('laboratory/orders/{laboratoryOrder}/results', LaboratoryResultEntry::class)->middleware('permission:laboratory-results.enter')->name('laboratory.results.entry');
        Route::get('laboratory/orders/{laboratoryOrder}/report', LaboratoryOrderReportController::class)->middleware('permission:laboratory-results.print')->name('laboratory.orders.report');
        Route::get('laboratory/results/{laboratoryResult}/verify', LaboratoryVerifyResult::class)->middleware('permission:laboratory-results.verify')->name('laboratory.results.verify');
        Route::get('laboratory/results/{laboratoryResult}/print', LaboratoryResultPrintController::class)->middleware('permission:laboratory-results.print')->name('laboratory.results.print');
        Route::get('laboratory/critical-results', LaboratoryCriticalResults::class)->middleware('permission:laboratory-critical-results.view')->name('laboratory.critical-results');
        Route::get('clinical/laboratory-results', ClinicalLaboratoryResults::class)->middleware('permission:laboratory-results.view')->name('clinical.laboratory-results');
        Route::get('pharmacy', PharmacyQueue::class)->middleware('permission:pharmacy.view-queue')->name('pharmacy.index');
        Route::get('pharmacy/dashboard', PharmacyDashboard::class)->middleware('permission:pharmacy.view-dashboard')->name('pharmacy.dashboard');
        Route::get('pharmacy/prescriptions/{prescription}', PharmacyPrescriptionShow::class)->middleware('permission:pharmacy.view-prescription')->name('pharmacy.prescriptions.show');
        Route::get('pharmacy/prescriptions/{prescription}/dispense', PharmacyDispensePrescription::class)->middleware('permission:pharmacy.dispense')->name('pharmacy.prescriptions.dispense');
        Route::get('pharmacy/dispensings/{dispensing}/labels', DispensingLabelController::class)->middleware('permission:pharmacy.print-labels')->name('pharmacy.dispensings.labels');
        Route::get('pharmacy/medicines', PharmacyMedicinesIndex::class)->middleware('permission:pharmacy.view-medicines')->name('pharmacy.medicines.index');
        Route::get('pharmacy/medicines/{medicine}/stock-card', PharmacyMedicineStockCard::class)->middleware('permission:pharmacy.view-stock-card')->name('pharmacy.medicines.stock-card');
        Route::get('pharmacy/opening-stock', PharmacyOpeningStock::class)->middleware('permission:pharmacy.opening-stock')->name('pharmacy.opening-stock');
        Route::get('pharmacy/purchase-orders', PharmacyPurchasesIndex::class)->middleware('permission:pharmacy.create-purchase-order|pharmacy.receive-stock')->name('pharmacy.purchase-orders.index');
        Route::get('pharmacy/purchase-orders/{purchaseOrder}', PharmacyPurchaseShow::class)->middleware('permission:pharmacy.create-purchase-order|pharmacy.receive-stock')->name('pharmacy.purchase-orders.show');
        Route::get('pharmacy/receipts', PharmacyReceiptsIndex::class)->middleware('permission:pharmacy.receive-stock')->name('pharmacy.receipts.index');
        Route::get('pharmacy/receipts/create', PharmacyReceiptCreate::class)->middleware('permission:pharmacy.receive-stock')->name('pharmacy.receipts.create');
        Route::get('pharmacy/receipts/{purchaseReceipt}', PharmacyReceiptShow::class)->middleware('permission:pharmacy.receive-stock')->name('pharmacy.receipts.show');
        Route::get('pharmacy/transfers', PharmacyTransfersIndex::class)->middleware('permission:pharmacy.transfer-stock')->name('pharmacy.transfers.index');
        Route::get('pharmacy/transfers/{stockTransfer}', PharmacyTransferShow::class)->middleware('permission:pharmacy.transfer-stock')->name('pharmacy.transfers.show');
        Route::get('pharmacy/adjustments', PharmacyAdjustmentsIndex::class)->middleware('permission:pharmacy.adjust-stock')->name('pharmacy.adjustments.index');
        Route::get('pharmacy/stock-counts', PharmacyStockCountsIndex::class)->middleware('permission:pharmacy.stock-count')->name('pharmacy.stock-counts.index');
        Route::get('pharmacy/stock-counts/{stockCount}', PharmacyStockCountShow::class)->middleware('permission:pharmacy.stock-count')->name('pharmacy.stock-counts.show');
        Route::get('pharmacy/returns', PharmacyReturnsIndex::class)->middleware('permission:pharmacy.manage-patient-returns')->name('pharmacy.returns.index');
        Route::get('pharmacy/supplier-returns', PharmacyReturnsIndex::class)->middleware('permission:pharmacy.return-to-supplier')->defaults('type', 'supplier')->name('pharmacy.supplier-returns.index');
        Route::get('settings/laboratory/categories', LaboratoryCategoriesIndex::class)->middleware('permission:laboratory.manage-test-categories')->name('settings.laboratory.categories');
        Route::get('settings/laboratory/specimens', LaboratorySpecimensIndex::class)->middleware('permission:laboratory.manage-specimens')->name('settings.laboratory.specimens');
        Route::get('settings/laboratory/tests', LaboratoryTestsIndex::class)->middleware('permission:laboratory.manage-tests')->name('settings.laboratory.tests');
        Route::get('settings/laboratory/tests/{laboratoryTest}', LaboratoryTestShow::class)->middleware('permission:laboratory.manage-tests')->name('settings.laboratory.tests.show');
        Route::get('settings/pharmacy/categories', PharmacySetupIndex::class)->middleware('permission:pharmacy.manage-medicine-categories')->defaults('section', 'categories')->name('settings.pharmacy.categories');
        Route::get('settings/pharmacy/generics', PharmacySetupIndex::class)->middleware('permission:pharmacy.manage-generics')->defaults('section', 'generics')->name('settings.pharmacy.generics');
        Route::get('settings/pharmacy/dosage-forms', PharmacySetupIndex::class)->middleware('permission:pharmacy.manage-dosage-forms')->defaults('section', 'dosage-forms')->name('settings.pharmacy.dosage-forms');
        Route::get('settings/pharmacy/units', PharmacySetupIndex::class)->middleware('permission:pharmacy.manage-units')->defaults('section', 'units')->name('settings.pharmacy.units');
        Route::get('settings/pharmacy/routes', PharmacySetupIndex::class)->middleware('permission:pharmacy.manage-routes')->defaults('section', 'routes')->name('settings.pharmacy.routes');
        Route::get('settings/pharmacy/suppliers', PharmacySetupIndex::class)->middleware('permission:pharmacy.manage-suppliers')->defaults('section', 'suppliers')->name('settings.pharmacy.suppliers');
        Route::get('settings/pharmacy/stock-locations', PharmacySetupIndex::class)->middleware('permission:pharmacy.manage-stock-locations')->defaults('section', 'stock-locations')->name('settings.pharmacy.stock-locations');
        Route::get('settings/observation/rooms', ObservationSettingsRooms::class)->middleware('permission:observation.manage-rooms')->name('settings.observation.rooms');
        Route::get('settings/observation/beds', ObservationSettingsBeds::class)->middleware('permission:observation.manage-beds')->name('settings.observation.beds');
        Route::get('settings/observation/services', ObservationSettingsServices::class)->middleware('permission:services.view')->name('settings.observation.services');
        Route::get('settings/observation/billing', ObservationSettingsBilling::class)->middleware('permission:observation.manage-billing')->name('settings.observation.billing');
        Route::get('settings/dental/findings', DentalSettingsFindings::class)->middleware('permission:dental.manage-odontogram')->name('settings.dental.findings');
        Route::get('settings/dental/services', DentalSettingsServices::class)->middleware('permission:services.view')->name('settings.dental.services');
        Route::get('settings/dental/procedure-types', DentalSettingsProcedureTypes::class)->middleware('permission:dental.manage-settings')->name('settings.dental.procedure-types');
        Route::get('settings/dental/procedure-templates', DentalSettingsProcedureTemplates::class)->middleware('permission:dental.manage-procedure-templates')->name('settings.dental.procedure-templates');
        Route::get('settings/dental/materials', DentalSettingsMaterials::class)->middleware('permission:dental.manage-materials')->name('settings.dental.materials');
        Route::get('settings/dental/anaesthetics', DentalSettingsAnaesthetics::class)->middleware('permission:dental.manage-anaesthetics')->name('settings.dental.anaesthetics');
        Route::get('settings/dental/consents', DentalSettingsConsents::class)->middleware('permission:dental.manage-consents')->name('settings.dental.consents');
        Route::get('settings/dental/appointment-types', DentalSettingsAppointmentTypes::class)->middleware('permission:dental.manage-settings')->name('settings.dental.appointment-types');
        Route::get('settings/dental/rooms', DentalSettingsRooms::class)->middleware('permission:dental.manage-rooms')->name('settings.dental.rooms');
        Route::get('settings/dental/chairs', DentalSettingsChairs::class)->middleware('permission:dental.manage-chairs')->name('settings.dental.chairs');
        Route::get('settings/dental/preferences', DentalSettingsPreferences::class)->middleware('permission:settings.update')->name('settings.dental.preferences');
        Route::get('settings/dental/report-settings', DentalSettingsPreferences::class)->middleware('permission:dental.manage-settings')->defaults('section', 'reports')->name('settings.dental.report-settings');
        Route::get('settings/billing/payment-methods', BillingPaymentMethods::class)->middleware('permission:billing.manage-payment-methods')->name('settings.billing.payment-methods');
        Route::get('settings/billing/preferences', BillingPreferences::class)->middleware('permission:billing.manage-settings')->name('settings.billing.preferences');
        foreach (['payment-rules', 'discount-rules', 'waiver-rules', 'receipt-settings', 'cashier-settings', 'credit-settings', 'report-settings'] as $section) {
            Route::get('settings/billing/'.$section, BillingPreferences::class)->middleware('permission:billing.manage-settings')->defaults('section', $section)->name('settings.billing.'.$section);
        }
        Route::get('reports/patients', PatientsReport::class)->middleware('permission:patients.export|reports.view')->name('reports.patients');
        Route::get('reports/patients/export', PatientReportExportController::class)->middleware('permission:patients.export|reports.view')->name('reports.patients.export');
        Route::get('reports/reception', ReceptionReport::class)->middleware('permission:patients.export|reports.view')->name('reports.reception');
        Route::get('reports/reception/export', ReceptionReportExportController::class)->middleware('permission:patients.export|reports.view')->name('reports.reception.export');
        Route::get('reports/triage', TriageReport::class)->middleware('permission:reports.view')->name('reports.triage');
        Route::get('reports/triage/export', TriageReportExportController::class)->middleware('permission:reports.view')->name('reports.triage.export');
        Route::get('reports/opd', OpdReport::class)->middleware('permission:reports.view')->name('reports.opd');
        Route::get('reports/opd/export', OpdReportExportController::class)->middleware('permission:reports.view')->name('reports.opd.export');
        foreach (['admissions', 'occupancy', 'length-of-stay', 'nursing', 'medication-administration', 'procedures', 'referrals', 'discharges', 'revenue', 'bed-cleaning'] as $type) {
            Route::get('reports/observation/'.$type, ObservationReport::class)->middleware('permission:observation.reports.view')->defaults('type', $type)->name('reports.observation.'.$type);
        }
        Route::get('reports/observation/{type}/export', ObservationReportExportController::class)->middleware('permission:observation.reports.export')->name('reports.observation.export');
        Route::get('reports/diagnoses', DiagnosesReport::class)->middleware('permission:reports.view')->name('reports.diagnoses');
        Route::get('reports/diagnoses/export', DiagnosisReportExportController::class)->middleware('permission:reports.view')->name('reports.diagnoses.export');
        foreach (['patients', 'diagnoses', 'findings', 'tooth-findings', 'procedures', 'extractions', 'restorations', 'periodontal', 'endodontics', 'orthodontics', 'treatment-plans', 'lab-orders', 'dental-lab', 'materials', 'revenue', 'provider-workload'] as $type) {
            Route::get('reports/dental/'.$type, DentalReport::class)->middleware('permission:dental.reports.view')->defaults('type', $type)->name('reports.dental.'.$type);
        }
        Route::get('reports/dental/{type}/export', DentalReportExportController::class)->middleware('permission:dental.reports.export')->name('reports.dental.export');
        foreach (['claims','claim-items','nhif-claim-report','rejections','resubmissions','outstanding','payments','reconciliation','provider-performance','service-utilization','member-utilization'] as $type) {
            Route::get('reports/insurance/'.$type, InsuranceReport::class)->middleware('permission:insurance.reports.view')->defaults('type', $type)->name('reports.insurance.'.$type);
        }
        Route::get('reports/insurance/{type}/export', InsuranceReportExportController::class)->middleware('permission:insurance.reports.export')->name('reports.insurance.export');
        foreach (['collections', 'pending', 'outstanding', 'invoices', 'payments', 'payment-methods', 'cashiers', 'discounts', 'waivers', 'refunds', 'reversals', 'deposits', 'credit-patients', 'department-revenue', 'service-revenue'] as $type) {
            Route::get('reports/billing/'.$type, BillingReport::class)->middleware('permission:billing.reports.view')->defaults('type', $type)->name('reports.billing.'.$type);
        }
        Route::get('reports/billing/{type}/export', BillingReportExportController::class)->middleware('permission:billing.reports.export')->name('reports.billing.export');
        Route::get('reports/referrals', ReferralsReport::class)->middleware('permission:reports.view')->name('reports.referrals');
        Route::get('reports/referrals/export', ReferralReportExportController::class)->middleware('permission:reports.view')->name('reports.referrals.export');
        Route::get('reports/laboratory/{type?}', LaboratoryReport::class)->middleware('permission:laboratory-reports.view')->name('reports.laboratory');
        Route::get('reports/laboratory/{type}/export', LaboratoryReportExportController::class)->middleware('permission:laboratory-reports.export')->name('reports.laboratory.export');
        Route::get('reports/pharmacy/{type?}', PharmacyReport::class)->middleware('permission:pharmacy.reports.view')->name('reports.pharmacy');
        Route::get('reports/pharmacy/{type}/export', PharmacyReportExportController::class)->middleware('permission:pharmacy.reports.export')->name('reports.pharmacy.export');
    });
});
