<div class="space-y-4">
    @unless($isReadOnly)
        <x-card>
            <div class="mb-4"><h3 class="font-semibold">Add Medicine</h3><p class="text-sm text-slate-500">Draft orders are billed only when the Dental encounter is completed.</p></div>
            <div class="grid gap-3 md:grid-cols-2">
                @if($medicines->isNotEmpty())
                    <x-text-input wire:model.live.debounce.300ms="medicineSearch" placeholder="Search medicine..." />
                    <div><x-select-input wire:model="prescriptionItemForm.medicine_id" class="w-full"><option value="">Select medicine</option>@foreach($medicines as $medicine)<option value="{{ $medicine->id }}" @disabled(! $medicine->billing_readiness['ready'])>{{ $medicine->name }} {{ $medicine->strength ? '· '.$medicine->strength : '' }} — {{ $medicine->billing_readiness['label'] }}</option>@endforeach</x-select-input><x-input-error :messages="$errors->get('prescriptionItemForm.medicine_id')" class="mt-1" /><p class="mt-1 text-xs text-slate-500">Unavailable medicines remain visible so Billing/Administrator can correct their configuration.</p></div>
                @else
                    <div class="md:col-span-2 rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-800 dark:border-amber-800 dark:bg-amber-950/20 dark:text-amber-200">No medicine is configured for this facility. Contact Pharmacy/Administrator to configure a medicine, billing service, and price.<x-input-error :messages="$errors->get('prescriptionItemForm.medicine_id')" class="mt-1" /></div>
                @endif
                <div><label class="mb-1 block text-sm font-medium">Dose</label><x-select-input wire:model.live="prescriptionItemForm.dose_choice" class="w-full"><option value="">Select dose</option>@foreach($doseOptions as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach @if($prescriptionItemForm->dose && ! array_key_exists($prescriptionItemForm->dose, $doseOptions))<option value="{{ $prescriptionItemForm->dose }}">{{ $prescriptionItemForm->dose }}</option>@endif<option value="custom">Custom</option></x-select-input>@if($prescriptionItemForm->dose_choice === 'custom')<x-text-input wire:model.live.debounce.300ms="prescriptionItemForm.custom_dose" placeholder="e.g. 500 mg or 1 capsule" class="mt-2 w-full" />@endif<x-input-error :messages="$errors->get('prescriptionItemForm.dose')" class="mt-1" /></div>
                <div><label class="mb-1 block text-sm font-medium">Frequency</label><x-select-input wire:model.live="prescriptionItemForm.frequency_choice" class="w-full"><option value="">Select frequency</option>@foreach(\App\Support\MedicationDirections::FREQUENCIES as $frequency)<option value="{{ $frequency }}">{{ $frequency }}</option>@endforeach<option value="custom">Custom</option></x-select-input>@if($prescriptionItemForm->frequency_choice === 'custom')<x-text-input wire:model.live.debounce.300ms="prescriptionItemForm.custom_frequency" placeholder="Describe the exact schedule" class="mt-2 w-full" />@endif<x-input-error :messages="$errors->get('prescriptionItemForm.frequency')" class="mt-1" /></div>
                <div><label class="mb-1 block text-sm font-medium">Duration</label>@unless(in_array($prescriptionItemForm->duration_unit, ['until_finished', 'single_dose'], true))<x-text-input type="number" min="1" wire:model.live="prescriptionItemForm.duration_value" placeholder="Duration" class="w-full" />@endunless<x-input-error :messages="$errors->get('prescriptionItemForm.duration_value')" class="mt-1" /></div>
                <div><label class="mb-1 block text-sm font-medium">Duration Unit</label><x-select-input wire:model.live="prescriptionItemForm.duration_unit" class="w-full"><option value="hours">Hours</option><option value="days">Days</option><option value="weeks">Weeks</option><option value="months">Months</option><option value="until_finished">Until finished</option><option value="single_dose">Single dose</option></x-select-input><x-input-error :messages="$errors->get('prescriptionItemForm.duration_unit')" class="mt-1" /></div>
                <div><label class="mb-1 block text-sm font-medium">Route</label><x-select-input wire:model.live="prescriptionItemForm.route_choice" class="w-full"><option value="">Select route</option>@foreach(\App\Support\MedicationDirections::ROUTES as $route)<option value="{{ $route }}">{{ $route }}</option>@endforeach<option value="custom">Other</option></x-select-input>@if($prescriptionItemForm->route_choice === 'custom')<x-text-input wire:model.live.debounce.300ms="prescriptionItemForm.custom_route" placeholder="Specify other route" class="mt-2 w-full" />@endif<x-input-error :messages="$errors->get('prescriptionItemForm.route')" class="mt-1" /></div>
                <div><label class="mb-1 block text-sm font-medium">Quantity</label><x-text-input type="number" min="1" step="0.01" wire:model.live.debounce.300ms="prescriptionItemForm.quantity" placeholder="Quantity" class="w-full" /><x-input-error :messages="$errors->get('prescriptionItemForm.quantity')" class="mt-1" />@if($prescriptionItemForm->calculation_summary)<p class="mt-1 text-xs text-emerald-700 dark:text-emerald-300">Calculated: {{ $prescriptionItemForm->calculation_summary }}</p>@elseif(in_array($prescriptionItemForm->frequency, ['As needed / PRN'], true) || $prescriptionItemForm->frequency_choice === 'custom')<p class="mt-1 text-xs text-amber-700 dark:text-amber-300">Quantity cannot be inferred for PRN/custom schedules. Enter and review it explicitly.</p>@endif @if($prescriptionItemForm->quantity_manually_adjusted)<p class="mt-1 text-xs font-medium text-amber-700 dark:text-amber-300">Manually adjusted quantity</p>@endif</div>
                <x-text-input wire:model="prescriptionItemForm.instructions" placeholder="Instructions" />
                <x-text-input wire:model="prescriptionItemForm.indication" placeholder="Indication" />
            </div>
            @if($editingPrescriptionItemId)<div class="mt-3 flex gap-2"><x-primary-button type="button" wire:click="updatePrescriptionItem">Update Medicine</x-primary-button><x-secondary-button type="button" wire:click="cancelPrescriptionEdit">Cancel</x-secondary-button></div>@else<x-primary-button type="button" wire:click="addPrescription" class="mt-3">Add Medication Order</x-primary-button>@endif
        </x-card>
    @endunless
    <x-card>
        <h3 class="mb-3 font-semibold">Active Medicine Orders</h3>
        <div class="space-y-3">
            @forelse($prescriptions as $prescription)
                @foreach($prescription->items as $item)
                    <div class="rounded-md border border-slate-200 p-3 dark:border-slate-700"><p class="font-medium">{{ $item->medication_name }}{{ $item->strength ? ' '.$item->strength : '' }}</p><dl class="mt-2 grid grid-cols-[auto_1fr] gap-x-2 gap-y-1 text-xs text-slate-500"><dt>Dose:</dt><dd>{{ $item->dose }}</dd><dt>Frequency:</dt><dd>{{ \App\Support\MedicationDirections::displayFrequency($item->frequency) }}</dd><dt>Duration:</dt><dd>{{ in_array($item->duration_unit, ['until_finished', 'single_dose'], true) ? str($item->duration_unit)->replace('_', ' ')->title() : $item->duration_value.' '.str($item->duration_unit)->replace('_', ' ') }}</dd><dt>Route:</dt><dd>{{ \App\Support\MedicationDirections::displayRoute($item->route) }}</dd><dt>Quantity:</dt><dd>{{ $item->quantity }} {{ \App\Support\MedicationDirections::quantityUnit($item->medicine, (float) $item->quantity) }}</dd></dl>@if(filled($item->instructions))<p class="mt-2 text-xs"><span class="font-medium">Instructions:</span> {{ $item->instructions }}</p>@endif @if(filled($item->indication))<p class="mt-1 text-xs"><span class="font-medium">Indication:</span> {{ $item->indication }}</p>@endif @can('update', $prescription)@if(! $isReadOnly && $prescription->isEditableDraft())<div class="mt-2 flex gap-3"><button type="button" wire:click="editPrescriptionItem({{ $item->id }})" class="text-xs font-semibold text-primary">Edit</button><button type="button" wire:click="removePrescriptionItem({{ $item->id }})" wire:confirm="Una uhakika unataka kuondoa dawa hii?" class="text-xs font-semibold text-red-600">Remove</button></div>@endif@endcan</div>
                @endforeach
                <p class="text-xs text-slate-500">{{ str($prescription->status->value)->replace('_', ' ')->title() }} · Source: Dental</p>
            @empty
                <p class="text-sm text-slate-500">No medicines ordered.</p>
            @endforelse
        </div>
    </x-card>
</div>
