<div class="space-y-6">
    <div class="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
        <div class="grid gap-3 md:grid-cols-3 lg:min-w-[720px]">
            <x-text-input wire:model.live.debounce.300ms="search" placeholder="Tafuta category..." />
            <x-select-input wire:model.live="type"><option value="">Types zote</option>@foreach($types as $type)<option value="{{ $type->value }}">{{ $type->label() }}</option>@endforeach</x-select-input>
            <x-select-input wire:model.live="status"><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">Zote</option></x-select-input>
        </div>
        @can('create', \App\Models\ServiceCategory::class)<x-primary-button wire:click="create"><x-lucide-plus class="h-4 w-4" /> Ongeza</x-primary-button>@endcan
    </div>
    <x-card>
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm dark:divide-slate-700"><thead><tr class="text-left text-xs font-semibold uppercase text-slate-500"><th class="px-4 py-3">Category</th><th>Code</th><th>Type</th><th>Department</th><th>Services</th><th>Status</th><th class="text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($categories as $category)<tr><td class="px-4 py-3 font-semibold">{{ $category->name }}</td><td>{{ $category->code }}</td><td>{{ $category->category_type->label() }}</td><td>{{ $category->department?->name ?? '-' }}</td><td>{{ $category->services_count }}</td><td><x-badge :tone="$category->is_active ? 'success' : 'danger'">{{ $category->is_active ? 'Active' : 'Inactive' }}</x-badge></td><td><div class="flex justify-end gap-2"><button wire:click="toggle({{ $category->id }})" class="rounded-md p-2 hover:bg-slate-100 dark:hover:bg-slate-800"><x-lucide-power class="h-4 w-4" /></button><button wire:click="edit({{ $category->id }})" class="rounded-md p-2 hover:bg-slate-100 dark:hover:bg-slate-800"><x-lucide-pencil class="h-4 w-4" /></button><button wire:click="delete({{ $category->id }})" wire:confirm="Futa category?" class="rounded-md p-2 text-danger hover:bg-red-50"><x-lucide-trash-2 class="h-4 w-4" /></button></div></td></tr>@empty<tr><td colspan="7" class="px-4 py-10"><x-empty-state icon="folder-open" title="Hakuna categories" message="Service categories zitaonekana hapa." /></td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $categories->links() }}</div>
    </x-card>
    <x-modal :show="$showFormModal" title="Service Category" close="$set('showFormModal', false)" maxWidth="2xl"><form wire:submit="save" class="space-y-4"><div class="grid gap-4 md:grid-cols-2"><div><x-input-label value="Name" /><x-text-input wire:model="form.name" /><x-input-error :messages="$errors->get('form.name')" /></div><div><x-input-label value="Code" /><x-text-input wire:model="form.code" /><x-input-error :messages="$errors->get('form.code')" /></div><div><x-input-label value="Type" /><x-select-input wire:model="form.category_type">@foreach($types as $type)<option value="{{ $type->value }}">{{ $type->label() }}</option>@endforeach</x-select-input></div><div><x-input-label value="Department" /><x-select-input wire:model="form.department_id"><option value="">None</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</x-select-input></div><div><x-input-label value="Icon" /><x-text-input wire:model="form.icon" /></div><div><x-input-label value="Color" /><x-text-input type="color" wire:model="form.color" /></div><div><x-input-label value="Sort" /><x-text-input type="number" wire:model="form.sort_order" /></div><label class="flex items-center gap-2 pt-6 text-sm"><x-checkbox wire:model="form.is_active" /> Active</label></div><div><x-input-label value="Description" /><x-textarea wire:model="form.description" /></div><div class="flex justify-end"><x-primary-button><x-lucide-save class="h-4 w-4" /> Hifadhi</x-primary-button></div></form></x-modal>
</div>
