<div class="space-y-4">
    <x-card>
        <form wire:submit="save" class="grid gap-4 lg:grid-cols-2">
            <label class="block"><span class="text-sm">Patient</span><select wire:model="form.patient_id" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900"><option value="">Select patient</option>@foreach($patients as $patient)<option value="{{ $patient->id }}">{{ $patient->fullName() }} · {{ $patient->patient_number }}</option>@endforeach</select>@error('form.patient_id')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <label class="block"><span class="text-sm">Department</span><select wire:model="form.department_id" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900"><option value="">Select department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select>@error('form.department_id')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <label class="block"><span class="text-sm">Doctor</span><select wire:model="form.staff_id" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900"><option value="">Any available doctor</option>@foreach($staff as $member)<option value="{{ $member->id }}">{{ $member->name }}</option>@endforeach</select>@error('form.staff_id')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <label class="block"><span class="text-sm">Service</span><select wire:model="form.service_id" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900"><option value="">Optional</option>@foreach($services as $service)<option value="{{ $service->id }}">{{ $service->name }}</option>@endforeach</select>@error('form.service_id')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <label class="block"><span class="text-sm">Appointment Type</span><select wire:model="form.appointment_type" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900"><option value="general_consultation">General Consultation</option><option value="follow_up_visit">Follow-up Visit</option><option value="review">Review</option><option value="laboratory">Laboratory</option><option value="dental">Dental</option><option value="anc">ANC</option><option value="pnc">PNC</option><option value="family_planning">Family Planning</option><option value="child_clinic">Child Clinic</option><option value="immunization">Immunization</option><option value="dressing">Dressing</option><option value="procedure">Procedure</option><option value="observation_review">Observation Review</option><option value="home_care">Home Care</option><option value="teleconsultation">Teleconsultation</option></select>@error('form.appointment_type')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <label class="block"><span class="text-sm">Priority</span><select wire:model="form.priority" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900"><option value="normal">Normal</option><option value="urgent">Urgent</option><option value="emergency">Emergency</option></select>@error('form.priority')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <label class="block"><span class="text-sm">Date</span><input type="date" wire:model="form.appointment_date" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900">@error('form.appointment_date')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <label class="block"><span class="text-sm">Time</span><input type="time" wire:model="form.appointment_time" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900">@error('form.appointment_time')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <label class="block"><span class="text-sm">Duration Minutes</span><input type="number" min="5" step="5" wire:model="form.estimated_duration" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900">@error('form.estimated_duration')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <label class="block lg:col-span-2"><span class="text-sm">Reason</span><input wire:model="form.reason" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900">@error('form.reason')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <label class="block lg:col-span-2"><span class="text-sm">Notes</span><textarea rows="3" wire:model="form.notes" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 dark:border-slate-700 dark:bg-slate-900"></textarea>@error('form.notes')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</label>
            <div class="flex justify-end gap-2 lg:col-span-2"><a href="{{ route('appointments.index') }}" class="rounded-md border border-slate-300 px-4 py-2 text-sm dark:border-slate-700">Cancel</a><x-primary-button type="submit" wire:loading.attr="disabled" wire:target="save">Save Appointment</x-primary-button></div>
        </form>
    </x-card>
</div>
