<?php

return [
    'defaults' => [
        'country' => 'Tanzania',
        'timezone' => 'Africa/Dar_es_Salaam',
        'currency' => 'TZS',
        'currency_symbol' => 'TSh',
        'date_format' => 'd/m/Y',
        'time_format' => 'H:i',
        'primary_color' => '#0F766E',
        'secondary_color' => '#14B8A6',
        'default_language' => 'sw',
        'fallback_language' => 'en',
    ],
    'settings' => [
        'accepts_insurance' => ['value' => false, 'type' => 'boolean', 'group' => 'insurance'],
        'nhif_enabled' => ['value' => false, 'type' => 'boolean', 'group' => 'insurance'],
        'other_insurance_enabled' => ['value' => false, 'type' => 'boolean', 'group' => 'insurance'],
        'enable_dark_mode' => ['value' => true, 'type' => 'boolean', 'group' => 'system'],
        'default_theme' => ['value' => 'system', 'type' => 'string', 'group' => 'system'],
        'enable_patient_numbers' => ['value' => true, 'type' => 'boolean', 'group' => 'numbering'],
        'patient_number_prefix' => ['value' => 'PAT', 'type' => 'string', 'group' => 'numbering'],
        'enable_receipt_numbers' => ['value' => true, 'type' => 'boolean', 'group' => 'numbering'],
        'receipt_number_prefix' => ['value' => 'RCT', 'type' => 'string', 'group' => 'numbering'],
        'enable_invoice_numbers' => ['value' => true, 'type' => 'boolean', 'group' => 'numbering'],
        'invoice_number_prefix' => ['value' => 'INV', 'type' => 'string', 'group' => 'numbering'],
        'fiscal_year_start_month' => ['value' => '7', 'type' => 'integer', 'group' => 'finance'],
        'require_payment_before_service' => ['value' => true, 'type' => 'boolean', 'group' => 'finance'],
        'charge_new_patient_registration' => ['value' => true, 'type' => 'boolean', 'group' => 'reception_billing'],
        'charge_returning_patient_registration' => ['value' => false, 'type' => 'boolean', 'group' => 'reception_billing'],
        'new_patient_registration_service_id' => ['value' => '', 'type' => 'string', 'group' => 'reception_billing'],
        'returning_patient_registration_service_id' => ['value' => '', 'type' => 'string', 'group' => 'reception_billing'],
        'patient_card_replacement_service_id' => ['value' => '', 'type' => 'string', 'group' => 'reception_billing'],
        'require_consultation_service' => ['value' => true, 'type' => 'boolean', 'group' => 'reception_billing'],
        'auto_add_registration_fee' => ['value' => true, 'type' => 'boolean', 'group' => 'reception_billing'],
        'auto_add_consultation_fee' => ['value' => true, 'type' => 'boolean', 'group' => 'reception_billing'],
        'allow_partial_payments' => ['value' => false, 'type' => 'boolean', 'group' => 'finance'],
        'enable_audit_logs' => ['value' => true, 'type' => 'boolean', 'group' => 'system'],
        'enable_file_attachments' => ['value' => true, 'type' => 'boolean', 'group' => 'system'],
        'enable_sms_notifications' => ['value' => false, 'type' => 'boolean', 'group' => 'notifications'],
        'enable_email_notifications' => ['value' => false, 'type' => 'boolean', 'group' => 'notifications'],
        'enable_whatsapp_notifications' => ['value' => false, 'type' => 'boolean', 'group' => 'notifications'],
    ],
];
