<?php

return [
    'dashboard' => ['label' => 'Dashibodi', 'permissions' => ['dashboard.view' => 'Kuangalia dashibodi']],
    'facility' => ['label' => 'Kituo', 'permissions' => ['facility.view' => 'Kuangalia kituo', 'facility.update' => 'Kubadilisha kituo']],
    'departments' => ['label' => 'Departments', 'permissions' => ['departments.view' => 'Kuangalia departments', 'departments.create' => 'Kuongeza department', 'departments.update' => 'Kubadilisha department', 'departments.delete' => 'Kufuta department', 'departments.activate' => 'Kuwasha/kuzima department']],
    'job-titles' => ['label' => 'Vyeo', 'permissions' => ['job-titles.view' => 'Kuangalia vyeo', 'job-titles.create' => 'Kuongeza cheo', 'job-titles.update' => 'Kubadilisha cheo', 'job-titles.delete' => 'Kufuta cheo', 'job-titles.activate' => 'Kuwasha/kuzima cheo']],
    'roles' => ['label' => 'Roles', 'permissions' => ['roles.view' => 'Kuangalia roles', 'roles.create' => 'Kuongeza role', 'roles.update' => 'Kubadilisha role', 'roles.delete' => 'Kufuta role', 'roles.assign-permissions' => 'Kuweka permissions']],
    'permissions' => ['label' => 'Permissions', 'permissions' => ['permissions.view' => 'Kuangalia permissions']],
    'service-categories' => ['label' => 'Service Categories', 'permissions' => ['service-categories.view' => 'Kuangalia service categories', 'service-categories.create' => 'Kuongeza service category', 'service-categories.update' => 'Kubadilisha service category', 'service-categories.delete' => 'Kufuta service category', 'service-categories.activate' => 'Kuwasha/kuzima service category']],
    'services' => ['label' => 'Services', 'permissions' => ['services.view' => 'Kuangalia services', 'services.create' => 'Kuongeza service', 'services.update' => 'Kubadilisha service', 'services.delete' => 'Kufuta service', 'services.activate' => 'Kuwasha/kuzima service', 'services.manage-prices' => 'Kusimamia bei', 'services.view-price-history' => 'Kuangalia historia ya bei']],
    'insurance-providers' => ['label' => 'Insurance Providers', 'permissions' => ['insurance-providers.view' => 'Kuangalia bima', 'insurance-providers.create' => 'Kuongeza bima', 'insurance-providers.update' => 'Kubadilisha bima', 'insurance-providers.delete' => 'Kufuta bima']],
    'corporate-accounts' => ['label' => 'Corporate Accounts', 'permissions' => ['corporate-accounts.view' => 'Kuangalia corporate accounts', 'corporate-accounts.create' => 'Kuongeza corporate account', 'corporate-accounts.update' => 'Kubadilisha corporate account', 'corporate-accounts.delete' => 'Kufuta corporate account']],
    'staff' => ['label' => 'Watumishi', 'permissions' => [
        'staff.view' => 'Kuangalia watumishi',
        'staff.create' => 'Kuongeza mtumishi',
        'staff.update' => 'Kubadilisha mtumishi',
        'staff.delete' => 'Kufuta mtumishi',
        'staff.activate' => 'Kuwezesha account',
        'staff.suspend' => 'Kusimamisha account',
        'staff.restore' => 'Kurudisha mtumishi',
        'staff.assign-role' => 'Kuweka role',
        'staff.assign-department' => 'Kuweka department',
        'staff.assign-direct-permission' => 'Kuweka direct permissions',
        'staff.reset-password' => 'Kubadilisha nenosiri',
        'staff.manage-employment' => 'Kusimamia ajira',
        'staff.manage-education' => 'Kusimamia elimu',
        'staff.verify-education' => 'Kuthibitisha elimu',
        'staff.manage-license' => 'Kusimamia leseni',
        'staff.verify-license' => 'Kuthibitisha leseni',
        'staff.manage-documents' => 'Kusimamia nyaraka',
        'staff.manage-signature' => 'Kusimamia signature ya mtumishi',
        'staff.verify-documents' => 'Kuthibitisha nyaraka',
        'staff.manage-emergency-contacts' => 'Kusimamia watu wa dharura',
        'staff.view-login-history' => 'Kuangalia historia ya login',
        'staff.view-activity' => 'Kuangalia activity ya mtumishi',
        'staff.export' => 'Ku-export ripoti ya watumishi',
        'staff.override-employee-number' => 'Kubadilisha namba ya mtumishi',
    ]],
    'patients' => ['label' => 'Wagonjwa', 'permissions' => ['patients.view' => 'Kuangalia wagonjwa', 'patients.create' => 'Kuongeza mgonjwa', 'patients.quick-register' => 'Quick registration', 'patients.update' => 'Kubadilisha mgonjwa', 'patients.archive' => 'Ku-archive mgonjwa', 'patients.restore' => 'Kurudisha mgonjwa', 'patients.override-number' => 'Kubadilisha namba ya mgonjwa', 'patients.override-duplicate-warning' => 'Kupita duplicate warning', 'patients.manage-payers' => 'Kusimamia payer profiles', 'patients.manage-documents' => 'Kusimamia nyaraka za mgonjwa', 'patients.export' => 'Ku-export wagonjwa', 'patients.print-card' => 'Kuprint patient card', 'patients.replace-card' => 'Kubadilisha au kureprint patient card']],
    'reception' => ['label' => 'Reception', 'permissions' => ['reception.access' => 'Kuingia reception', 'reception.register-patient' => 'Kusajili mgonjwa', 'reception.open-visit' => 'Kufungua visit', 'reception.update-visit' => 'Kubadilisha visit', 'reception.cancel-visit' => 'Kufuta/cancel visit', 'reception.transfer-patient' => 'Transfer patient', 'reception.manage-queue' => 'Kusimamia foleni', 'reception.override-active-visit' => 'Kupita active visit warning', 'reception.exempt-payment' => 'Kusamehe malipo', 'reception.view-charge-preview' => 'Kuangalia charge preview', 'reception.override-registration-charge' => 'Kubadilisha registration charge', 'reception.override-consultation-charge' => 'Kubadilisha consultation charge', 'reception.waive-registration-fee' => 'Kusamehe registration fee', 'reception.waive-consultation-fee' => 'Kusamehe consultation fee']],
    'invoices' => ['label' => 'Invoices', 'permissions' => ['invoices.view' => 'Kuangalia invoices', 'invoices.create' => 'Kuunda invoice', 'invoices.cancel' => 'Cancel invoice', 'invoices.view-items' => 'Kuangalia invoice items']],
    'triage' => ['label' => 'Triage', 'permissions' => ['triage.access' => 'Kuingia triage', 'triage.view' => 'Kuangalia triage', 'triage.record-vitals' => 'Kurekodi vitals', 'triage.complete' => 'Kukamilisha triage', 'triage.amend' => 'Kufanya amendment ya triage', 'triage.override-payment' => 'Kupita kizuizi cha malipo', 'triage.set-emergency-priority' => 'Kuweka emergency priority', 'triage.transfer' => 'Kuhamisha mgonjwa triage']],
    'opd' => ['label' => 'OPD', 'permissions' => ['opd.access' => 'Kuingia OPD', 'opd.view-queue' => 'Kuangalia OPD queue', 'opd.assign-clinician' => 'Kumpangia clinician', 'opd.start-consultation' => 'Kuanza consultation', 'opd.consult' => 'Consultation', 'opd.complete-consultation' => 'Kukamilisha consultation', 'opd.transfer-patient' => 'Kuhamisha mgonjwa', 'opd.view-clinical-history' => 'Kuangalia historia ya clinical', 'opd.diagnose' => 'Diagnosis', 'opd.prescribe' => 'Kuandika prescription', 'opd.order-lab' => 'Kuomba vipimo']],
    'clinical-encounters' => ['label' => 'Clinical Encounters', 'permissions' => ['clinical-encounters.view' => 'Kuangalia encounters', 'clinical-encounters.create' => 'Kuunda encounter', 'clinical-encounters.update-draft' => 'Kuhifadhi draft', 'clinical-encounters.complete' => 'Kukamilisha encounter', 'clinical-encounters.amend' => 'Kufanya amendment', 'clinical-encounters.print' => 'Kuprint consultation summary']],
    'diagnoses' => ['label' => 'Diagnoses', 'permissions' => ['diagnoses.view' => 'Kuangalia diagnoses', 'diagnoses.create' => 'Kuongeza diagnosis', 'diagnoses.update' => 'Kubadilisha diagnosis', 'diagnoses.mark-error' => 'Ku-mark entered in error']],
    'laboratory-orders' => ['label' => 'Lab Orders', 'permissions' => ['laboratory-orders.view' => 'Kuangalia lab orders', 'laboratory-orders.create' => 'Kuunda lab order', 'laboratory-orders.cancel' => 'Kufuta lab order']],
    'prescriptions' => ['label' => 'Prescriptions', 'permissions' => ['prescriptions.view' => 'Kuangalia prescriptions', 'prescriptions.create' => 'Kuandika prescription', 'prescriptions.update' => 'Kubadilisha prescription', 'prescriptions.cancel' => 'Kufuta prescription']],
    'procedure-orders' => ['label' => 'Procedure Orders', 'permissions' => ['procedure-orders.view' => 'Kuangalia procedure orders', 'procedure-orders.create' => 'Kuunda procedure order', 'procedure-orders.cancel' => 'Kufuta procedure order']],
    'appointments' => ['label' => 'Appointments', 'permissions' => ['appointments.view' => 'Kuangalia appointments', 'appointments.create' => 'Kuunda appointment', 'appointments.update' => 'Kubadilisha appointment', 'appointments.cancel' => 'Kufuta appointment']],
    'referrals' => ['label' => 'Referrals', 'permissions' => ['referrals.view' => 'Kuangalia referrals', 'referrals.create' => 'Kuunda referral', 'referrals.update' => 'Kubadilisha referral', 'referrals.cancel' => 'Kufuta referral', 'referrals.print' => 'Kuprint referral']],
    'clinical-alerts' => ['label' => 'Clinical Alerts', 'permissions' => ['clinical-alerts.view' => 'Kuangalia alerts', 'clinical-alerts.acknowledge' => 'Ku-acknowledge alert', 'clinical-alerts.resolve' => 'Kuresolve alert', 'clinical-alerts.dismiss' => 'Kudismiss alert']],
    'laboratory' => ['label' => 'Maabara', 'permissions' => [
        'laboratory.access' => 'Kuingia maabara',
        'laboratory.view-dashboard' => 'Kuangalia dashboard ya maabara',
        'laboratory.view-queue' => 'Kuangalia foleni ya maabara',
        'laboratory.view-order' => 'Kuangalia order ya maabara',
        'laboratory.manage-test-categories' => 'Kusimamia laboratory categories',
        'laboratory.manage-tests' => 'Kusimamia vipimo vya maabara',
        'laboratory.manage-specimens' => 'Kusimamia specimen types',
        'laboratory.manage-parameters' => 'Kusimamia test parameters',
        'laboratory.manage-reference-ranges' => 'Kusimamia reference ranges',
        'laboratory.manage-panels' => 'Kusimamia test panels',
        'laboratory.collect-sample' => 'Kuchukua sample',
        'laboratory.receive-sample' => 'Kupokea sample',
        'laboratory.accept-sample' => 'Kukubali sample',
        'laboratory.reject-sample' => 'Kukataa sample',
        'laboratory.request-recollection' => 'Kuomba sample mpya',
        'laboratory.dispose-sample' => 'Kudispose sample',
        'laboratory.print-sample-label' => 'Kuprint sample label',
        'laboratory.override-payment' => 'Kupita payment block',
        'laboratory-results.view' => 'Kuangalia results',
        'laboratory-results.enter' => 'Kuingiza results',
        'laboratory-results.update-draft' => 'Kubadilisha draft',
        'laboratory-results.submit' => 'Kutuma results kwa uhakiki',
        'laboratory-results.verify' => 'Kuhakiki results',
        'laboratory-results.release' => 'Kutoa results',
        'laboratory-results.amend' => 'Kufanya amendment ya results',
        'laboratory-results.mark-error' => 'Ku-mark result error',
        'laboratory-results.print' => 'Kuprint result',
        'laboratory-results.view-history' => 'Kuangalia result history',
        'laboratory-critical-results.view' => 'Kuangalia critical results',
        'laboratory-critical-results.notify' => 'Kurekodi notification',
        'laboratory-critical-results.acknowledge' => 'Ku-acknowledge critical result',
        'laboratory-critical-results.resolve' => 'Kuresolve critical result',
        'laboratory-outsourced-tests.manage' => 'Kusimamia outsourced tests',
        'laboratory-reports.view' => 'Kuangalia ripoti za maabara',
        'laboratory-reports.export' => 'Ku-export ripoti za maabara',
    ]],
    'pharmacy' => ['label' => 'Famasi', 'permissions' => [
        'pharmacy.access' => 'Kuingia famasi',
        'pharmacy.view-dashboard' => 'Kuangalia dashboard ya famasi',
        'pharmacy.view-queue' => 'Kuangalia foleni ya prescription',
        'pharmacy.view-prescription' => 'Kuangalia prescription',
        'pharmacy.review-prescription' => 'Kufanya review ya prescription',
        'pharmacy.dispense' => 'Kutoa dawa',
        'pharmacy.partial-dispense' => 'Kutoa dawa kwa sehemu',
        'pharmacy.cancel-dispensing' => 'Kufuta dispensing',
        'pharmacy.reverse-dispensing' => 'Kureverse dispensing',
        'pharmacy.override-payment' => 'Kupita kizuizi cha malipo',
        'pharmacy.allow-negative-stock' => 'Kuruhusu negative stock',
        'pharmacy.substitute-equivalent' => 'Kubadilisha dawa equivalent',
        'pharmacy.substitute-non-equivalent' => 'Kubadilisha dawa non-equivalent',
        'pharmacy.print-labels' => 'Kuprint labels',
        'pharmacy.view-allergies' => 'Kuangalia allergies',
        'pharmacy.manage-medicine-categories' => 'Kusimamia medicine categories',
        'pharmacy.manage-generics' => 'Kusimamia generic medicines',
        'pharmacy.manage-dosage-forms' => 'Kusimamia dosage forms',
        'pharmacy.manage-units' => 'Kusimamia medicine units',
        'pharmacy.manage-routes' => 'Kusimamia routes of administration',
        'pharmacy.view-medicines' => 'Kuangalia medicines',
        'pharmacy.manage-medicines' => 'Kusimamia medicines',
        'pharmacy.manage-suppliers' => 'Kusimamia suppliers',
        'pharmacy.manage-stock-locations' => 'Kusimamia stock locations',
        'pharmacy.manage-prices' => 'Kusimamia bei za dawa',
        'pharmacy.view-stock' => 'Kuangalia stock',
        'pharmacy.opening-stock' => 'Kuweka opening stock',
        'pharmacy.create-purchase-order' => 'Kuunda purchase order',
        'pharmacy.receive-stock' => 'Kupokea stock',
        'pharmacy.verify-receipt' => 'Kuhakiki receipt',
        'pharmacy.transfer-stock' => 'Kuhamisha stock',
        'pharmacy.approve-transfer' => 'Kuapprove transfer',
        'pharmacy.receive-transfer' => 'Kupokea transfer',
        'pharmacy.adjust-stock' => 'Kurekebisha stock',
        'pharmacy.approve-adjustment' => 'Kuapprove adjustment',
        'pharmacy.stock-count' => 'Kuhesabu stock',
        'pharmacy.verify-stock-count' => 'Kuhakiki stock count',
        'pharmacy.post-stock-count' => 'Kupost stock count',
        'pharmacy.manage-expiry' => 'Kusimamia expiry',
        'pharmacy.quarantine-batch' => 'Kuquarantine batch',
        'pharmacy.recall-batch' => 'Kurecall batch',
        'pharmacy.return-to-supplier' => 'Kurudisha kwa supplier',
        'pharmacy.manage-patient-returns' => 'Kusimamia returns za mgonjwa',
        'pharmacy.view-stock-card' => 'Kuangalia stock card',
        'pharmacy.view-cost' => 'Kuangalia gharama',
        'pharmacy.view-stock-value' => 'Kuangalia thamani ya stock',
        'pharmacy.reports.view' => 'Kuangalia pharmacy reports',
        'pharmacy.reports.export' => 'Ku-export pharmacy reports',
    ]],
    'observation' => ['label' => 'Bed Rest / Uangalizi', 'permissions' => [
        'observation.access' => 'Kuingia Bed Rest / Uangalizi',
        'observation.view-dashboard' => 'Kuangalia dashboard ya observation',
        'observation.view-bed-board' => 'Kuangalia ramani ya vitanda',
        'observation.manage-rooms' => 'Kusimamia rooms za observation',
        'observation.manage-beds' => 'Kusimamia vitanda',
        'observation.reserve-bed' => 'Kureserve kitanda',
        'observation.admit' => 'Kulaza observation',
        'observation.override-payment' => 'Kupita payment block',
        'observation.assign-bed' => 'Kumpa kitanda',
        'observation.transfer-bed' => 'Kuhamisha kitanda',
        'observation.release-bed' => 'Kuachia kitanda',
        'observation.manage-bed-cleaning' => 'Kusimamia usafi wa kitanda',
        'observation.view-admission' => 'Kuangalia admission ya observation',
        'observation.update-admission' => 'Kubadilisha admission ya observation',
        'observation.record-nursing-observation' => 'Kurekodi nursing observation',
        'observation.amend-nursing-observation' => 'Kufanya amendment ya nursing observation',
        'observation.manage-schedules' => 'Kusimamia observation schedules',
        'observation.manage-nursing-tasks' => 'Kusimamia nursing tasks',
        'observation.create-handover' => 'Kuunda handover',
        'observation.acknowledge-handover' => 'Ku-acknowledge handover',
        'observation.create-order' => 'Kuunda doctor order',
        'observation.acknowledge-order' => 'Ku-acknowledge order',
        'observation.complete-order' => 'Kukamilisha order',
        'observation.cancel-order' => 'Kufuta order',
        'observation.administer-medication' => 'Kurekodi dawa iliyotolewa',
        'observation.record-iv-fluid' => 'Kurekodi IV fluid',
        'observation.record-oxygen' => 'Kurekodi oxygen therapy',
        'observation.record-nebulization' => 'Kurekodi nebulization',
        'observation.record-procedure' => 'Kurekodi bedside procedure',
        'observation.record-intake-output' => 'Kurekodi intake/output',
        'observation.clinical-review' => 'Kufanya clinical review',
        'observation.discharge' => 'Kuruhusu mgonjwa',
        'observation.authorize-discharge' => 'Ku-authorize discharge',
        'observation.refer' => 'Kutoa referral',
        'observation.record-lama' => 'Kurekodi LAMA',
        'observation.record-absconded' => 'Kurekodi absconded patient',
        'observation.record-death' => 'Kurekodi death foundation',
        'observation.print-chart' => 'Kuprint observation chart',
        'observation.print-discharge' => 'Kuprint discharge summary',
        'observation.view-billing' => 'Kuangalia billing ya observation',
        'observation.manage-billing' => 'Kusimamia billing ya observation',
        'observation.reports.view' => 'Kuangalia observation reports',
        'observation.reports.export' => 'Ku-export observation reports',
    ]],
    'dental' => ['label' => 'Dental', 'permissions' => [
        'dental.access' => 'Kuingia dental',
        'dental.view-dashboard' => 'Kuangalia dashboard ya dental',
        'dental.view-queue' => 'Kuangalia foleni ya dental',
        'dental.assign-dentist' => 'Kumpangia dentist',
        'dental.start-consultation' => 'Kuanza dental consultation',
        'dental.consult' => 'Dental consultation',
        'dental.complete-consultation' => 'Kukamilisha dental consultation',
        'dental.override-payment' => 'Kupita payment block',
        'dental.view-history' => 'Kuangalia dental history',
        'dental.manage-odontogram' => 'Kusimamia odontogram',
        'dental.add-finding' => 'Kuongeza finding',
        'dental.edit-finding' => 'Kubadilisha finding',
        'dental.mark-finding-error' => 'Ku-mark finding error',
        'dental.manage-periodontal-chart' => 'Kusimamia periodontal chart',
        'dental.create-diagnosis' => 'Kuongeza dental diagnosis',
        'dental.update-diagnosis' => 'Kubadilisha dental diagnosis',
        'dental.create-treatment-plan' => 'Kuunda treatment plan',
        'dental.update-treatment-plan' => 'Kubadilisha treatment plan',
        'dental.approve-treatment-plan' => 'Kuapprove treatment plan',
        'dental.cancel-treatment-plan' => 'Kucancel treatment plan',
        'dental.print-treatment-plan' => 'Kuprint treatment plan',
        'dental.perform-preventive-care' => 'Preventive care',
        'dental.perform-restorative-treatment' => 'Restorative treatment',
        'dental.perform-orthodontic-treatment' => 'Orthodontic treatment',
        'dental.perform-oral-surgery' => 'Oral surgery',
        'dental.perform-cosmetic-treatment' => 'Cosmetic treatment',
        'dental.perform-periodontal-treatment' => 'Periodontal treatment',
        'dental.amend-procedure' => 'Amend procedure',
        'dental.print-procedure-report' => 'Kuprint procedure report',
        'dental.manage-materials' => 'Kusimamia dental materials',
        'dental.use-materials' => 'Kutumia materials',
        'dental.view-material-cost' => 'Kuangalia gharama za materials',
        'dental.manage-consents' => 'Kusimamia dental consents',
        'dental.manage-attachments' => 'Kusimamia dental attachments',
        'dental.manage-dental-lab-orders' => 'Kusimamia dental lab orders',
        'dental.manage-orthodontic-cases' => 'Kusimamia orthodontic cases',
        'dental.manage-endodontic-cases' => 'Kusimamia endodontic cases',
        'dental.create-prescription' => 'Kuandika dental prescription',
        'dental.create-appointment' => 'Kuunda dental appointment',
        'dental.refer' => 'Kutoa dental referral',
        'dental.send-to-observation' => 'Kutuma observation',
        'dental.view-billing' => 'Kuangalia dental billing',
        'dental.manage-billing' => 'Kusimamia dental billing',
        'dental.reports.view' => 'Kuangalia dental reports',
        'dental.reports.export' => 'Ku-export dental reports',
        'dental.print-chart' => 'Kuprint dental chart',
    ]],
    'rch' => ['label' => 'RCH', 'permissions' => ['rch.access' => 'Kuingia RCH', 'rch.manage-anc' => 'ANC', 'rch.manage-family-planning' => 'Family planning', 'rch.manage-child-growth' => 'Child growth', 'rch.manage-immunization' => 'Immunization']],
    'bed-rest' => ['label' => 'Bed Rest', 'permissions' => ['bed-rest.access' => 'Kuingia bed rest', 'bed-rest.admit' => 'Kulaza', 'bed-rest.record-nursing-care' => 'Nursing care', 'bed-rest.administer-medication' => 'Kutoa dawa', 'bed-rest.discharge' => 'Kuruhusu', 'bed-rest.refer' => 'Referral']],
    'billing' => ['label' => 'Billing', 'permissions' => ['billing.access' => 'Kuingia billing', 'billing.create-invoice' => 'Invoice', 'billing.receive-payment' => 'Kupokea malipo', 'billing.refund' => 'Refund', 'billing.apply-discount' => 'Discount']],
    'accounting' => ['label' => 'Uhasibu', 'permissions' => ['accounting.access' => 'Kuingia uhasibu', 'accounting.manage-income' => 'Mapato', 'accounting.manage-expenses' => 'Matumizi', 'accounting.view-reports' => 'Ripoti', 'accounting.close-shift' => 'Kufunga shift']],
    'insurance' => ['label' => 'Bima', 'permissions' => ['insurance.access' => 'Kuingia bima', 'insurance.manage-members' => 'Members', 'insurance.create-claim' => 'Claim', 'insurance.submit-claim' => 'Submit claim', 'insurance.update-claim-status' => 'Claim status', 'insurance.view-nhif-report' => 'NHIF report']],
    'reports' => ['label' => 'Ripoti', 'permissions' => ['reports.view' => 'Kuangalia ripoti', 'reports.export-pdf' => 'PDF', 'reports.export-excel' => 'Excel', 'reports.view-financial' => 'Ripoti za fedha']],
    'settings' => ['label' => 'Mipangilio', 'permissions' => ['settings.view' => 'Kuangalia mipangilio', 'settings.update' => 'Kubadilisha mipangilio']],
    'audit-logs' => ['label' => 'Audit Logs', 'permissions' => ['audit-logs.view' => 'Kuangalia audit logs']],
];
